### ISSUE TITLE
Ground literals not updated with same objects

### ISSUE THREAD

**Issue by ryangpeixu** [tomsilver/pddlgym#57]
_compute_all_ground_literals seems to only be called from _update_objects_from_state which returns if the objects are the same (potentially causing a problem when transitioning to a problem with the same objects as the previous problem?)

**Comment by tomsilver** [comment]
Thanks! Confirmed that this is a bug. Will address soon.

**Comment by ronuchit** [comment]
@ryangpeixu I'd like to help you resolve this issue. Unfortunately, I wasn't able to reproduce it. Please see https://github.com/tomsilver/pddlgym/commit/17ba95acb3b6ede5caa67a21dd1dca7dbf007ac8, where I added a test for an environment with two problems that have the same object set. When I go from one problem to the next, the env.action_space is correctly updated.

Are you, perhaps, not using dynamic_action_space=True? Or maybe you could look at my test and let me know how it diverges from your own setting.

**Comment by ronuchit** [comment]
Oh, I think I found a way to replicate your issue...stay tuned...

**Comment by ronuchit** [comment]
Ok I think this is fixed in https://github.com/tomsilver/pddlgym/commit/8cd700dd4c3e4be24f507d99a1392c17994ec39c, along with a test that only passes after the fix.

The bug is quite subtle because it only surfaces in cases where `all_ground_literals` is different between the episodes while the object set is the same. `all_ground_literals` is the set of delete-relaxed-reachable literals, which means that this issue DOES NOT surface in classical blocksworld, because you can make any literal true from any initial state. Removing the `pickup` and `stack` operators from my test allowed the issue to surface.

@ryangpeixu let me know if the fix works for you (I just added a `action_space.reset_objects` function that is called upon `env.reset()`. Feel free to close the issue if so.

**Comment by ryangpeixu** [comment]
Yep! I'm pretty sure the issue is fixed now. Thanks!
