### ISSUE TITLE
Different representations of an action ?

### ISSUE THREAD

**Issue by aymeric75** [tomsilver/pddlgym#83]
Hello,

For my research I would need different representation of an action, i.e. for one same action, I would need different descriptions, from the more descriptive to the less descriptive.

Here is an example, with pddlgym for Hanoi-4-4, when I print out a sampled action, I get:
`move(d1:default,peg3:default)`

But I would like, for instance, something more descriptive like
`move d1 from tower1 where d2 already present to tower2 which is empty `

Is it possible ?

Thanks

(by the way, I don't understand what the "default" means)

**Comment by ronuchit** [comment]
If you print out the state (observation), you should see that it's a set of literals describing what disks are currently on what towers. With that information plus the action, you should be able to construct those sorts of descriptions themselves; we don't have that functionality built-in. You can look at some of the functions in the rendering code to help you out, since the rendering logic is very similar to what you're trying to do (except that you want to generate natural language rather than an image). The rendering code: https://github.com/tomsilver/pddlgym/blob/master/pddlgym/rendering/hanoi.py

**Comment by ronuchit** [comment]
Sorry, regarding your last point -- "default" refers to the type of the object. In this environment, there are no types, but since the PDDLGym library expects all objects to be typed, we just give everything the type "default". An alternative would have been for us to have two different object types: disk and tower.

**Comment by aymeric75** [comment]
> If you print out the state (observation), you should see that it's a set of literals describing what disks are currently on what towers. With that information plus the action, you should be able to construct those sorts of descriptions themselves; we don't have that functionality built-in. You can look at some of the functions in the rendering code to help you out, since the rendering logic is very similar to what you're trying to do (except that you want to generate natural language rather than an image). The rendering code: https://github.com/tomsilver/pddlgym/blob/master/pddlgym/rendering/hanoi.py

I will check this out, thanks a lot
