### ISSUE TITLE
Trying to set a seed, but not working

### ISSUE THREAD

**Issue by aymeric75** [tomsilver/pddlgym#89]
Hi,

I tried to set a seed so that I can sample the exact same amount of unique observations in my code:
```

import pddlgym
import imageio
import numpy as np
import matplotlib.pyplot as plt

nb_samplings_per_starting_state = 201

env = pddlgym.make("PDDLEnvHanoi-v0", dynamic_action_space=True, seed=1)

env.seed(1)

unique_obs = []

for ii in range(1):

    # Initializing the first State
    obs, debug_info = env.reset(_problem_idx=0)

    img, peg_to_disc_list = env.render()

    if str(peg_to_disc_list) not in unique_obs:
        unique_obs.append(str(peg_to_disc_list))


    # looping over the nber of states to sample for each starting position
    for jjj in range(nb_samplings_per_starting_state):
        
        print("counter: {}".format(str(jjj)))

        # sample an action
        action = env.action_space.sample(obs)

        # apply the action and retrieve obs
        obs, reward, done, debug_info = env.step(action)

        img, peg_to_disc_list = env.render()

        if str(peg_to_disc_list) not in unique_obs:
            unique_obs.append(str(peg_to_disc_list))


print("len unique_obs")
print(len(unique_obs))

```

But this is not working, it prints always a different number.

**Comment by aymeric75** [comment]
(sorry for the "spams" but I really did not find an answer)

**Comment by ronuchit** [comment]
@tomsilver  could you take a look at this one?

**Comment by tomsilver** [comment]
Hi @aymeric75, I'm not able to reproduce the issue because the code snippet above doesn't run for me. The line `env.reset(_problem_idx=0)` crashes with `TypeError: reset() got an unexpected keyword argument '_problem_idx'`. Is it possible that you made local modifications to the reset method? Can you try to create a minimal example with a fresh install of pddlgym?

I do have a hunch about what might be going on though. You may need to seed the action space separately from the environment seed call, as in:

```
env.seed(1)
env.action_space.seed(1)
```

Hopefully that fixes things, but if not, let us know (and re-open this issue).
